version: "3.9"

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: my_database
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  server:
    build: ./server
    restart: always
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: my_database
    volumes:
      - .:/app
    ports:
      - "3001:3001"
    depends_on:
      - db

  client:
    build: ./client
    restart: always
    environment:
      REACT_APP_API_URL: "http://localhost:3000"
    volumes:
      - ./client:/app
    ports:
      - "3000:3000"
    depends_on:
      - server

volumes:
  db-data:
